### ISSUE TITLE
Does it work with develop version of MODX?

### ISSUE THREAD

**Issue by gadamiak** [BobRay/CacheMaster#1]
I installed CacheMaster in develop version of MODX, namely from the Git develop branch (2.3.0-dev). I used both default and custom plugin settings (via property set). But it doesn't seem to work. My resources don't get refreshed even on changing the `content` field.

The site is installed with a custom config key so the cache files sit in a subfolder of `core/cache/`. The error log shows nothing. What's the problem?

**Comment by BobRay** [comment]
I'm closing this. Let me know if it's still a problem.
