### ISSUE TITLE
Context property

### ISSUE THREAD

**Issue by sottwell** [BobRay/CacheMaster#2]
It would be very nice if CachMaster had a property for specifying a context in which to disable the automatic cache clearing button. Probably should take a comma-delimited list, with “all” being the default.

**Comment by BobRay** [comment]
Sorry, I must have missed this message.  I'm not sure I understand. CM clears the specific cache file for the object being saved -- nothing else. If you manually check the "Empty Cache" box, MODX clears the cache as usual (doing whatever it does). Not sure how Contexts would figure into this process.
