### ISSUE TITLE
Cachemaster 1.2.2 and Revo 2.3.2 on Modxcloud.com

### ISSUE THREAD

**Issue by hcanning2014** [BobRay/CacheMaster#4]
Hi Bob,
New to cachemaster and it doesnt seem to be working.
I call my templates using the include snippet e.g.
1

[[include? &file=`assets/templates/index.php`]]

Say I have 2 pages Home and About

Home - uncached it has 10 queries and cached it has 1 if
1

<meta name="generator" content="Query time: [^qt^] ([^q^] Queries) // Parse time: [^p^] // Total time: [^t^] // Source: [^s^]">
is correct
About - uncached it has 12 queries and cached it has 1

Lets say CacheMaster is installed and both Home and About are currently cached and use 1 query. If I update Home and navigate to About and View source it states I am making 12 queries again instead of 1 implying that the entire site cache has been cleared and not just that of the Home page. I use the default settings in Cache Master properties and the Empty Cache checkbox is checked by default on all my resources.

Am I missing something? I'm also hosted on modxcloud.com

Thanks

**Comment by BobRay** [comment]
Sorry I missed this. There was a problem with getting GitHub notifications. I'm closing this, but let me know if it's still a problem.
