### ISSUE TITLE
CacheMaster won't install

### ISSUE THREAD

**Issue by smxi** [BobRay/CacheMaster#6]
I'm trying to put cachemaster on a production server, and it won't 'install'. It downloads correctly, extracts correctly, I've confirmed and explicitly set modx-core/components/ to 777 just in case that matters, though it shouldn't.

When I click on on the 'install' nothing happens. I can view the 'about', check for updates, all that, but it simply won't install.

I successfully installed the plugin on my dev server, which tends to have looser permissions than the live server, so I suspect some directory has to have some permissions, but I can't find which it is. Obviously if a directly needs to be writeable for installation that should be checked by the thing being installed as a matter of course, so if that's the problem, this would be a bug issue, not just an install issue.

I've searched my local system for all files/directories with 'cachemaster' after the successful install, and can't find any more directories where permissions might be an issue.

I tried 'updating' another out of date plugin on the live server, and it updated fine, no issues.

**Comment by BobRay** [comment]
CacheManager's files are copied to their locations in core/components, but that's true of any extra. 

Setting core/components to 777 could cause things to hang on many servers running suPhp, suExec, or something similar. They won't execute PHP script files unless the folder/file permissions are 755/644.

Is there anything relevant in the MODX error log?

The CM install is very straightforward. It creates the plugin, and it connects the plugin to various System Events. Any extra with a plugin would do the same thing.

**Comment by smxi** [comment]
This is unlikely to be a cachemaster issue after looking at the site modx errors.

 [2017-03-15 16:12:31] (ERROR @ /connectors/index.php) MODX could not download the file. You must enable allow_url_fopen, cURL or fsockopen to use remote transport packaging.
[2017-03-15 16:12:31] (ERROR @ /connectors/index.php) Could not transfer package articles-1.6.4-pl/xPDOTransportVehicle/009f020dd4e6e1a9f49335a1d1b4c94e/archivist-1.2.4-pl.transport.zip to /usr/home/immediateann/public_html/immediateannuities.com/modxr-core/packages/.

that's how the page load for packages always starts with errors. Note that cURL is enabled, allow_url_fopen is disabled on the live server, and packages are downloading fine, I can see the files in core/packages, timestamped and all for cachemaster. This error message to me clearly indicates modx needs to have a temp download location but it can't write to it, so it, incorrectly, assumes the problem is the missing downloader tool.

It's like something is stuck somewhere, and blocks any further install actions.

Modx complained when I changed core/components to 755, said it wasn't writable, so I made it 757, which made modx happy. Then I also set the files in it to 646.

I've had these types of odd permissions issues with modx before, but I can't make heads or tails of this one.

This is a general package install issue, however, not a cachemaster issue. I tried reinstalling some we don't use and they won't reinstall. Or install, for that matter. Glad I picked ones we don't, use.

I know in my previous modx permisisons issues, the problem was in another area, that modx wasn't checking.

**Comment by smxi** [comment]
https://forums.modx.com/?action=thread&thread=75714

this is the problem, I have all these packages, I see now. It's Articles creating the mess/taglister . You should ban that package until it's fixed.

**Comment by BobRay** [comment]
I think it's the Articles uninstall that messes things up.  Because it installs several sub-packages (Quip, archivist, etc.) they don't all get totally removed when you uninstall Articles. I once had to comb through the DB to get rid of some leftover Articles sub-package detritus.

**Comment by smxi** [comment]
Do you remember which tables the stuff was in? Is there some way to get this articles plugin removed from the core modx plugins? it's lethal and shouldn't be connected with something as overall good as modx. I still can't install your cachemaster on the live server, but for some reason despite ongoing errors internally, it did install on my dev server.
